# fly.toml app configuration file generated for questplatform on 2024-01-17T15:22:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "questplatform"
primary_region = "arn"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-8x"
  memory = "2gb"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[services.concurrency]
  type = "requests"
  hard_limit = 8
  soft_limit = 7
