# Generated by Django 5.0.1 on 2024-01-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_test_tipo_alter_test_duratamax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='dataOraInizio',
            field=models.DateTimeField(null=True),
        ),
    ]
