# Generated by Django 5.0.1 on 2024-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_test_insequenza_test_nrgruppo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='nrGruppo',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
