# Generated by Django 5.0.1 on 2024-01-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_test_nrgruppo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Domande_Varianti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.domande')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.test')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.varianti')),
            ],
        ),
    ]
