# Generated by Django 5.0.1 on 2024-01-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_test_domande_varianti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='domanda',
            new_name='idDomanda',
        ),
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='test',
            new_name='idTest',
        ),
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='variante',
            new_name='idVariante',
        ),
        migrations.RenameField(
            model_name='test_utenti',
            old_name='test',
            new_name='idTest',
        ),
        migrations.RenameField(
            model_name='test_utenti',
            old_name='utente',
            new_name='idUtente',
        ),
        migrations.RenameField(
            model_name='varianti',
            old_name='domanda',
            new_name='idDomanda',
        ),
    ]
