# Generated by Django 5.0.1 on 2024-01-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_test_nrgruppo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='idDomanda',
            new_name='domanda',
        ),
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='idTest',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='test_domande_varianti',
            old_name='idVariante',
            new_name='variante',
        ),
        migrations.RenameField(
            model_name='test_utenti',
            old_name='idTest',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='test_utenti',
            old_name='idUtente',
            new_name='utente',
        ),
        migrations.RenameField(
            model_name='varianti',
            old_name='idDomanda',
            new_name='domanda',
        ),
    ]
