# Generated by Django 5.0.1 on 2024-02-04 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_test_utente_delete_test_utenti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsGroup',
            fields=[
                ('idGruppi', models.AutoField(primary_key=True, serialize=False)),
                ('nrTest', models.IntegerField(default=0)),
                ('nrGruppo', models.IntegerField(default=0)),
                ('tipo', models.CharField(default='manuale', max_length=50)),
                ('inSequenza', models.BooleanField(default=False)),
                ('secondiRitardo', models.IntegerField(default=1)),
                ('dataOraInizio', models.DateTimeField(null=True)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
