# Generated by Django 5.0.1 on 2024-02-08 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_test_dataorainserimento_test_dataorafine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dataOraInserimento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
