# Generated by Django 5.0.1 on 2024-01-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domande',
            fields=[
                ('idDomanda', models.AutoField(primary_key=True, serialize=False)),
                ('corpo', models.CharField(max_length=100)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idTest', models.AutoField(primary_key=True, serialize=False)),
                ('durataMax', models.IntegerField()),
                ('dataOraInizio', models.DateTimeField(auto_now_add=True)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('idUtente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('ruolo', models.CharField(max_length=30)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Utenti',
            fields=[
                ('idTest_Utenti', models.AutoField(primary_key=True, serialize=False)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('idTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.test')),
                ('idUtente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.utenti')),
            ],
        ),
        migrations.CreateModel(
            name='Varianti',
            fields=[
                ('idVariante', models.AutoField(primary_key=True, serialize=False)),
                ('corpo', models.CharField(max_length=100)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('idDomanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.domande')),
            ],
        ),
    ]
