# Generated by Django 5.0.1 on 2024-01-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_utenti',
            old_name='idTest',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='test_utenti',
            old_name='idUtente',
            new_name='utente',
        ),
        migrations.RenameField(
            model_name='varianti',
            old_name='idDomanda',
            new_name='domanda',
        ),
    ]
