# Generated by Django 5.0.1 on 2024-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_test_utenti_utente_delete_utenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tipo',
            field=models.CharField(default='manuale', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='durataMax',
            field=models.IntegerField(default=60),
        ),
    ]
