# Generated by Django 5.0.1 on 2024-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_test_dataorainizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='inSequenza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='nrGruppo',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
