# Generated by Django 5.0.1 on 2024-01-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_iddomanda_test_domande_varianti_domanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='secondiRitardo',
            field=models.IntegerField(default=1),
        ),
    ]
