# Generated by Django 5.0.1 on 2024-01-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_test_secondiritardo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistiche',
            fields=[
                ('idStatistica', models.AutoField(primary_key=True, serialize=False)),
                ('tempo', models.FloatField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.test')),
            ],
        ),
    ]
