# Generated by Django 5.0.1 on 2024-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_statistiche_dataorainserimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='dataOraInserimento',
        ),
        migrations.AddField(
            model_name='test',
            name='dataOraFine',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Statistiche',
        ),
    ]
