# Generated by Django 5.0.1 on 2024-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_test_dataorainserimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='tipo',
            field=models.CharField(default='t', max_length=100),
        ),
        migrations.AddField(
            model_name='varianti',
            name='rispostaEsatta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
