# Generated by Django 5.0.1 on 2024-02-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_statistiche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfide',
            fields=[
                ('idSfida', models.AutoField(primary_key=True, serialize=False)),
                ('nrGruppo', models.IntegerField(default=0)),
                ('tipo', models.CharField(default='manuale', max_length=50)),
                ('secondiRitardo', models.IntegerField(default=1)),
                ('dataOraInizio', models.DateTimeField(null=True)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('vincitore', models.CharField(default='pareggio', max_length=50)),
                ('utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='utente', to=settings.AUTH_USER_MODEL)),
                ('utenteSfidato', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='utenteSfidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
