# Generated by Django 5.0.1 on 2024-02-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_sfide'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nrTest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sfide',
            name='tipo',
            field=models.CharField(default='sfida', max_length=50),
        ),
    ]
