# Generated by Django 5.0.1 on 2024-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_test_nrtest_alter_sfide_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domande',
            name='tipo',
            field=models.IntegerField(default=-1),
        ),
    ]
