# Generated by Django 5.0.1 on 2024-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_domande_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='numeroPagina',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='domande',
            name='tipo',
            field=models.CharField(default='t', max_length=100),
        ),
    ]
