# Generated by Django 5.0.1 on 2024-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_domande_numeropagina_alter_domande_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domande',
            name='numeroPagina',
        ),
    ]
