# Generated by Django 5.0.1 on 2024-03-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_remove_domande_numeropagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='numeroPagine',
            field=models.IntegerField(default=-1),
        ),
    ]
