# Generated by Django 5.0.1 on 2024-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_domande_numeropagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='malusF5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='numeroErrori',
            field=models.IntegerField(default=0),
        ),
    ]
