# Generated by Django 5.0.1 on 2024-05-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_test_malusf5_test_numeroerrori'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_domande_varianti',
            name='nrPagina',
            field=models.IntegerField(default=0),
        ),
    ]
