# Generated by Django 5.0.1 on 2024-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_test_domande_varianti_nrpagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
    ]
