# Generated by Django 5.0.1 on 2024-05-20 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_domande_attivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domande',
            index=models.Index(fields=['corpo'], name='webapp_doma_corpo_2f602b_idx'),
        ),
        migrations.AddIndex(
            model_name='domande',
            index=models.Index(fields=['dataOraInserimento'], name='webapp_doma_dataOra_57fead_idx'),
        ),
        migrations.AddIndex(
            model_name='domande',
            index=models.Index(fields=['tipo'], name='webapp_doma_tipo_2090a4_idx'),
        ),
        migrations.AddIndex(
            model_name='domande',
            index=models.Index(fields=['attivo'], name='webapp_doma_attivo_d786ea_idx'),
        ),
        migrations.AddIndex(
            model_name='domande',
            index=models.Index(fields=['numeroPagine'], name='webapp_doma_numeroP_2e1888_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['utente'], name='webapp_sfid_utente__6d541c_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['utenteSfidato'], name='webapp_sfid_utenteS_7768a1_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['nrGruppo'], name='webapp_sfid_nrGrupp_f768e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['dataOraInserimento'], name='webapp_sfid_dataOra_23fa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['dataOraInizio'], name='webapp_sfid_dataOra_c143e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sfide',
            index=models.Index(fields=['tipo'], name='webapp_sfid_tipo_12e885_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiche',
            index=models.Index(fields=['utente'], name='webapp_stat_utente__64ba64_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiche',
            index=models.Index(fields=['tipoDomanda'], name='webapp_stat_tipoDom_3e0f85_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiche',
            index=models.Index(fields=['nrErrori'], name='webapp_stat_nrError_1f417d_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['utente'], name='webapp_test_utente__bd75ec_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['nrGruppo'], name='webapp_test_nrGrupp_5d7e03_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['dataOraInserimento'], name='webapp_test_dataOra_d4119f_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['dataOraInizio'], name='webapp_test_dataOra_be2002_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['dataOraFine'], name='webapp_test_dataOra_c1b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['tipo'], name='webapp_test_tipo_c8d1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='test_domande_varianti',
            index=models.Index(fields=['test'], name='webapp_test_test_id_a17937_idx'),
        ),
        migrations.AddIndex(
            model_name='test_domande_varianti',
            index=models.Index(fields=['domanda'], name='webapp_test_domanda_ea6075_idx'),
        ),
        migrations.AddIndex(
            model_name='test_domande_varianti',
            index=models.Index(fields=['variante'], name='webapp_test_variant_95f89c_idx'),
        ),
        migrations.AddIndex(
            model_name='testsgroup',
            index=models.Index(fields=['utente'], name='webapp_test_utente__59b794_idx'),
        ),
        migrations.AddIndex(
            model_name='testsgroup',
            index=models.Index(fields=['nrGruppo'], name='webapp_test_nrGrupp_83428c_idx'),
        ),
        migrations.AddIndex(
            model_name='testsgroup',
            index=models.Index(fields=['dataOraInserimento'], name='webapp_test_dataOra_d7a8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='testsgroup',
            index=models.Index(fields=['dataOraInizio'], name='webapp_test_dataOra_4d451f_idx'),
        ),
        migrations.AddIndex(
            model_name='testsgroup',
            index=models.Index(fields=['tipo'], name='webapp_test_tipo_c6e6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='varianti',
            index=models.Index(fields=['domanda'], name='webapp_vari_domanda_947b80_idx'),
        ),
        migrations.AddIndex(
            model_name='varianti',
            index=models.Index(fields=['corpo'], name='webapp_vari_corpo_aee970_idx'),
        ),
        migrations.AddIndex(
            model_name='varianti',
            index=models.Index(fields=['dataOraInserimento'], name='webapp_vari_dataOra_137ff6_idx'),
        ),
    ]
