# Generated by Django 5.0.1 on 2024-05-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_domande_webapp_doma_corpo_2f602b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='domande',
            name='webapp_doma_numeroP_2e1888_idx',
        ),
        migrations.RemoveIndex(
            model_name='sfide',
            name='webapp_sfid_dataOra_23fa5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='sfide',
            name='webapp_sfid_tipo_12e885_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistiche',
            name='webapp_stat_tipoDom_3e0f85_idx',
        ),
        migrations.RemoveIndex(
            model_name='statistiche',
            name='webapp_stat_nrError_1f417d_idx',
        ),
        migrations.RemoveIndex(
            model_name='test',
            name='webapp_test_dataOra_d4119f_idx',
        ),
        migrations.RemoveIndex(
            model_name='testsgroup',
            name='webapp_test_nrGrupp_83428c_idx',
        ),
    ]
