# Generated by Django 5.0.2 on 2024-02-26 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domande',
            fields=[
                ('idDomanda', models.AutoField(primary_key=True, serialize=False)),
                ('corpo', models.CharField(max_length=100)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='t', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idTest', models.AutoField(primary_key=True, serialize=False)),
                ('nrGruppo', models.IntegerField(default=0)),
                ('tipo', models.CharField(default='manuale', max_length=50)),
                ('inSequenza', models.BooleanField(default=False)),
                ('secondiRitardo', models.IntegerField(default=1)),
                ('dataOraInizio', models.DateTimeField(null=True)),
                ('dataOraFine', models.DateTimeField(null=True)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestsGroup',
            fields=[
                ('idGruppi', models.AutoField(primary_key=True, serialize=False)),
                ('nrTest', models.IntegerField(default=0)),
                ('nrGruppo', models.IntegerField(default=0)),
                ('tipo', models.CharField(default='manuale', max_length=50)),
                ('inSequenza', models.BooleanField(default=False)),
                ('secondiRitardo', models.IntegerField(default=1)),
                ('dataOraInizio', models.DateTimeField(null=True)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Varianti',
            fields=[
                ('idVariante', models.AutoField(primary_key=True, serialize=False)),
                ('corpo', models.CharField(max_length=100)),
                ('dataOraInserimento', models.DateTimeField(auto_now_add=True)),
                ('rispostaEsatta', models.CharField(default='', max_length=100)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.domande')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Domande_Varianti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.domande')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.test')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.varianti')),
            ],
        ),
    ]
